version: '3.4'

services:
  api:
    image: remind-api
    restart: always
    ports:
      - "5252:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__DefaultConnection=server=database; database=RemindDb; user=root; password=/Chimbatata265
    volumes:
      - "C:\\remind\\api:/data"
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "C:/remind/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=/Chimbatata265